server:
  port: 8082
spring:
  application:
    name: ApiController
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes[0]:
        id: users-status-check
        uri: lb://PhotoAppAPIUsers
        predicates[0]: Path=/users-ws/users/status/check
        predicates[1]: Method=GET
        filters[0]: RemoveRequestHeader=Cookie
        filters[1]: RewritePath=/users-ws/users/status/check, /users/status/check
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
