server:
  port: 8082
spring:
  application:
    name: ApiController
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes[0]:
        id: users-status-check
        uri: lb://PhotoAppAPIUsers
        predicates[0]: Path=/users/status/check
        predicates[1]: Method=GET, POST
        predicates[2]: Header=Authorization, Bearer (.*)
        filters[0]: RemoveRequestHeader=Cookie
        filters[1]: AuthorizationHeaderFilter
#        filters[1]: RewritePath=/users-ws/users/status/check, /users/status/check
      routes[1]:
        id: users
        uri: lb://PhotoAppAPIUsers
        predicates[0]: Path=/users
        predicates[1]: Method=GET, POST
        filters[0]: RemoveRequestHeader=Cookie
      routes[2]:
        id: h2console
        uri: lb://PhotoAppAPIUsers
        predicates[0]: Path=/h2-console
        predicates[1]: Method=GET
        filters[0]: RemoveRequestHeader=Cookie
      routes[3]:
        id: login
        uri: lb://PhotoAppAPIUsers
        predicates[0]: Path=/login
        predicates[1]: Method=POST
        filters[0]: RemoveRequestHeader=Cookie
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
token:
  secret: djhfjdjfdkfkdifkkjdsyfidudjhfjdjfdkfkdifkkjdsyfidudjhfjdjfdkfkdifkkjdsyfidu
